#!/bin/bash
#
# Copyright (C) 2014 Eric Schulte
# Licensed under the Gnu Public License Version 3 or later
#
# Instrument an assembly program with assembler instructions to label
# all comparison operations.
#
HELP="Usage: $0 [OPTION]... [INPUT-ASM-FILE]
 Options:
  -i[SUFFIX] -------- edit file in place (optional backup at SUFFIX)"
eval set -- $(getopt hi:: "$@" || echo "$HELP" && exit 1;)
RATE=0.1
SED_OPTS=" "
while [ $# -gt 0 ];do
    case $1 in
        -h)  echo "$HELP"; exit 0;;
        -i)  SED_OPTS+="$1$2"; shift;;
        (--) shift; break;;
        (-*) echo "$HELP" && exit 1;;
        (*)  break;;
    esac
    shift
done

ADJ=$(echo "scale=0;((1 - $RATE) * 65535)/1"|bc)
SED_CMD="
# the macro used to label comparison instructions
1i\\
$(cat <<"EOF"|sed 's/\\/\\\\/g;s/\t/\\t/g;s/$/\\/;'|sed "s/ADJ/$ADJ/"
	.macro ___mk_labeled cmd, first, second
___mk_ur_enter_\@:
	\cmd    \first, \second
___mk_ur_exit_\@:
EOF
)
\\t.endm

# replace all comparison instructions with macro calls
s/\(^[[:space:]]\)\(cmp[^[:space:]]*\)\([[:space:]]*\)/\1___mk_labeled\3\2, /"

sed $SED_OPTS "$SED_CMD" $@
# echo "$SED_CMD"
